os: Visual Studio 2015

install:
  - cmd: refreshenv
  - cmd: set
  - cmd: python --version
  - cmd: wmic OS get OSArchitecture

build: off

build_script:
  - "python tests.py"

artifacts:
  - path: tmp
    name: tmp
    type: zip
