os: Visual Studio 2015

install:
  - cmd: refreshenv
  - cmd: set
  - cmd: python --version
  - cmd: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe"

build: off

build_script:
  - "python test.py"

test_script:
  - "python test.py"
