os: Visual Studio 2015

install:
  - cmd: refreshenv
  - cmd: set
  - cmd: python --version
  - cmd: wmic OS get OSArchitecture

build: off

build_script:
  - "python obj_test.py"
  - "python lib_test.py"
  - "python pe_test_projects.py"

artifacts:
  - path: tmp
    name: obj
    type: zip
  - path: tmp-lib
    name: lib
    type: zip

